### ISSUE TITLE
expected enum `Result`, found enum `Option`

### ISSUE THREAD

**Issue by m50046208** [iouts/db_export#1]
cargo 编译抛出错误
 --> src\main.rs:25:15
   |
25 |     while let Some(row) = cursor.next().unwrap() {
   |               ^^^^^^^^^   ---------------------- this expression has type `Result<sqlite::Row, sqlite::Error>`
   |               |
   |               expected enum `Result`, found enum `Option`
   |
   = note: expected enum `Result<sqlite::Row, sqlite::Error>`
              found enum `Option<_>`

直接用release里面的  exe 文件，
decompress error: corrupt deflate stream
thread 'tokio-runtime-worker' panicked at 'range end index 12 out of range for slice of length 0', library\core\src\slice\index.rs:73:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by iouts** [comment]
第一个问题是因为sqlite的更新。第二个问题是在处理哪个文件的时候遇到的？
